"use client";
import { useParams } from "next/navigation";
import { useLanguage } from "../../_components/useLanguage";

const sampleResourcesByCategory: Record<string, Array<{ title: string; desc: string; tagColor: string }>> = {
  math: [
    { title: "Solve for x: 3x + 7 = 22", desc: "3x = 22 - 7 → 3x = 15 → x = 5", tagColor: "#ef4444" },
    { title: "Solve for x: 5x - 10 = 20", desc: "5x = 20 + 10 → 5x = 30 → x = 6", tagColor: "#ef4444" },
    { title: "Solve for x: 4x + 9 = 25", desc: "4x = 25 - 9 → 4x = 16 → x = 4", tagColor: "#ef4444" },
    { title: "Solve for x: 7x - 14 = 35", desc: "7x = 35 + 14 → 7x = 49 → x = 7", tagColor: "#ef4444" },
    { title: "Solve for x: 2x + 8 = 18", desc: "2x = 18 - 8 → 2x = 10 → x = 5", tagColor: "#ef4444" },
    { title: "Solve for x: 9x - 27 = 0", desc: "9x = 27 → x = 3", tagColor: "#ef4444" },
    { title: "Solve for x: 6x + 12 = 48", desc: "6x = 48 - 12 → 6x = 36 → x = 6", tagColor: "#ef4444" },
    { title: "Solve for x: 8x - 16 = 40", desc: "8x = 40 + 16 → 8x = 56 → x = 7", tagColor: "#ef4444" },
    { title: "Solve for x: x + 15 = 28", desc: "x = 28 - 15 → x = 13", tagColor: "#ef4444" },
    { title: "Solve for x: 10x = 90", desc: "x = 9", tagColor: "#ef4444" },
    { title: "Solve for x: 12x - 24 = 48", desc: "12x = 48 + 24 → 12x = 72 → x = 6", tagColor: "#ef4444" },
    { title: "Solve for x: 15x + 5 = 80", desc: "15x = 80 - 5 → 15x = 75 → x = 5", tagColor: "#ef4444" },
    { title: "Solve for x: 14x - 28 = 56", desc: "14x = 56 + 28 → 14x = 84 → x = 6", tagColor: "#ef4444" },
    { title: "Solve for x: 11x + 22 = 55", desc: "11x = 55 - 22 → 11x = 33 → x = 3", tagColor: "#ef4444" },
    { title: "Solve for x: 13x - 39 = 0", desc: "13x = 39 → x = 3", tagColor: "#ef4444" },
    { title: "From y = ln(6-x), find x", desc: "6 - x = eʸ → x = 6 - eʸ", tagColor: "#ef4444" },
    { title: "From y = ln(10-x), find x", desc: "10 - x = eʸ → x = 10 - eʸ", tagColor: "#ef4444" },
    { title: "From y = ln(8-x), find x", desc: "8 - x = eʸ → x = 8 - eʸ", tagColor: "#ef4444" },
    { title: "From y = ln(12-x), find x", desc: "12 - x = eʸ → x = 12 - eʸ", tagColor: "#ef4444" },
    { title: "From y = ln(15-x), find x", desc: "15 - x = eʸ → x = 15 - eʸ", tagColor: "#ef4444" },
    { title: "Solve for x: 18x + 6 = 96", desc: "18x = 96 - 6 → 18x = 90 → x = 5", tagColor: "#ef4444" },
    { title: "Solve for x: 20x - 40 = 60", desc: "20x = 60 + 40 → 20x = 100 → x = 5", tagColor: "#ef4444" },
    { title: "Solve for x: 16x + 32 = 80", desc: "16x = 80 - 32 → 16x = 48 → x = 3", tagColor: "#ef4444" },
    { title: "Solve for x: 25x = 125", desc: "x = 5", tagColor: "#ef4444" },
    { title: "Solve for x: 30x - 90 = 0", desc: "30x = 90 → x = 3", tagColor: "#ef4444" },
    { title: "From y = ln(20-x), find x", desc: "20 - x = eʸ → x = 20 - eʸ", tagColor: "#ef4444" },
    { title: "From y = ln(9-x), find x", desc: "9 - x = eʸ → x = 9 - eʸ", tagColor: "#ef4444" },
    { title: "From y = ln(25-x), find x", desc: "25 - x = eʸ → x = 25 - eʸ", tagColor: "#ef4444" },
    { title: "Solve for x: 50x + 100 = 350", desc: "50x = 350 - 100 → 50x = 250 → x = 5", tagColor: "#ef4444" },
    { title: "Solve for x: 45x - 90 = 135", desc: "45x = 135 + 90 → 45x = 225 → x = 5", tagColor: "#ef4444" },
  ],
  statistics: [
    { title: "Calculate standard deviation of a dataset", desc: "Find the mean of the data set. Subtract the mean from each value and square the result. Find the average of those squared differences. Take the square root.", tagColor: "#3b82f6" },
    { title: "Find the probability of independent events", desc: "For independent events A and B, P(A and B) = P(A) × P(B)", tagColor: "#3b82f6" },
    { title: "Find the mean of numbers 4, 6, 8", desc: "Mean = (4 + 6 + 8) / 3 = 18 / 3 = 6", tagColor: "#3b82f6" },
    { title: "Find the median of 2, 5, 7, 9, 12", desc: "Middle value = 7 → Median = 7", tagColor: "#3b82f6" },
    { title: "Find the mode of 3, 4, 4, 5, 6", desc: "Most repeated number = 4 → Mode = 4", tagColor: "#3b82f6" },
    { title: "Find the range of 10, 15, 22, 30", desc: "Range = Highest - Lowest = 30 - 10 = 20", tagColor: "#3b82f6" },
    { title: "Find probability of getting head in a coin toss", desc: "P(Head) = 1 / 2", tagColor: "#3b82f6" },
    { title: "Find probability of rolling a 3 on a die", desc: "P(3) = 1 / 6", tagColor: "#3b82f6" },
    { title: "Find mean of 5, 10, 15, 20", desc: "Mean = (5 + 10 + 15 + 20) / 4 = 50 / 4 = 12.5", tagColor: "#3b82f6" },
    { title: "Find the median of 1, 3, 5, 7", desc: "Median = (3 + 5) / 2 = 4", tagColor: "#3b82f6" },
    { title: "Find the mode of 2, 2, 3, 4, 5", desc: "Mode = 2", tagColor: "#3b82f6" },
    { title: "Find the range of 8, 12, 20, 25", desc: "Range = 25 - 8 = 17", tagColor: "#3b82f6" },
    { title: "Find probability of drawing a king from 52 cards", desc: "P(King) = 4 / 52 = 1 / 13", tagColor: "#3b82f6" },
    { title: "Find probability of getting even number on a die", desc: "Even numbers = 2, 4, 6 → P(Even) = 3 / 6 = 1 / 2", tagColor: "#3b82f6" },
    { title: "Find mean of 12, 18, 24", desc: "Mean = (12 + 18 + 24) / 3 = 54 / 3 = 18", tagColor: "#3b82f6" },
    { title: "Find median of 6, 8, 10, 12, 14", desc: "Median = 10", tagColor: "#3b82f6" },
    { title: "Find mode of 7, 7, 9, 10", desc: "Mode = 7", tagColor: "#3b82f6" },
    { title: "Find range of 100, 120, 150, 170", desc: "Range = 170 - 100 = 70", tagColor: "#3b82f6" },
    { title: "Find probability of selecting red card from deck", desc: "Red cards = 26 → P(Red) = 26 / 52 = 1 / 2", tagColor: "#3b82f6" },
    { title: "Find mean of 2, 4, 6, 8, 10", desc: "Mean = (2 + 4 + 6 + 8 + 10) / 5 = 30 / 5 = 6", tagColor: "#3b82f6" },
    { title: "Find median of 11, 13, 15", desc: "Median = 13", tagColor: "#3b82f6" },
    { title: "Find mode of 5, 5, 5, 8, 9", desc: "Mode = 5", tagColor: "#3b82f6" },
    { title: "Find probability of getting odd number on die", desc: "Odd numbers = 1, 3, 5 → P(Odd) = 3 / 6 = 1 / 2", tagColor: "#3b82f6" },
    { title: "Find range of 45, 55, 60, 90", desc: "Range = 90 - 45 = 45", tagColor: "#3b82f6" },
    { title: "Find mean of 14, 16, 18, 20", desc: "Mean = (14 + 16 + 18 + 20) / 4 = 68 / 4 = 17", tagColor: "#3b82f6" },
    { title: "Find median of 4, 8, 12, 16", desc: "Median = (8 + 12) / 2 = 10", tagColor: "#3b82f6" },
    { title: "Find probability of getting ace from cards", desc: "Aces = 4 → P(Ace) = 4 / 52 = 1 / 13", tagColor: "#3b82f6" },
    { title: "Find mode of 1, 2, 2, 2, 5", desc: "Mode = 2", tagColor: "#3b82f6" },
    { title: "Find range of 5, 15, 25, 35", desc: "Range = 35 - 5 = 30", tagColor: "#3b82f6" },
    { title: "Find probability of head twice in two tosses", desc: "P(HH) = 1/2 × 1/2 = 1/4", tagColor: "#3b82f6" },
    { title: "Find mean of 9, 12, 15", desc: "Mean = (9 + 12 + 15) / 3 = 36 / 3 = 12", tagColor: "#3b82f6" },
    { title: "Find median of 20, 25, 30, 35, 40", desc: "Median = 30", tagColor: "#3b82f6" },
    { title: "Find mode of 8, 8, 10, 12", desc: "Mode = 8", tagColor: "#3b82f6" },
    { title: "Find probability of getting number less than 4 on die", desc: "Numbers less than 4 = 1, 2, 3 → P = 3 / 6 = 1 / 2", tagColor: "#3b82f6" },
    { title: "Calculate variance of a dataset", desc: "Find the mean. Subtract the mean from each value. Square each result. Find the average of squared differences.", tagColor: "#3b82f6" },
  ],
  calculus: [
    { title: "Find the limit of a rational function", desc: "Evaluate lim(x→c) of (x² - c²)/(x - c). Factor numerator: (x² - c²) = (x - c)(x + c). Cancel (x - c). Result = x + c. Put x = c → Limit = 2c", tagColor: "#8b5cf6" },
    { title: "Power Rule of Integration", desc: "∫xⁿ dx = (xⁿ⁺¹)/(n+1) + C where n ≠ -1", tagColor: "#8b5cf6" },
    { title: "Differentiate x³", desc: "d/dx (x³) = 3x²", tagColor: "#8b5cf6" },
    { title: "Integrate x²", desc: "∫x² dx = x³/3 + C", tagColor: "#8b5cf6" },
    { title: "Find derivative of 5x⁴", desc: "d/dx (5x⁴) = 20x³", tagColor: "#8b5cf6" },
    { title: "Integrate 4x³", desc: "∫4x³ dx = x⁴ + C", tagColor: "#8b5cf6" },
    { title: "Differentiate 7x²", desc: "d/dx (7x²) = 14x", tagColor: "#8b5cf6" },
    { title: "Integrate 6x", desc: "∫6x dx = 3x² + C", tagColor: "#8b5cf6" },
    { title: "Find derivative of 9x⁵", desc: "d/dx (9x⁵) = 45x⁴", tagColor: "#8b5cf6" },
    { title: "Integrate x⁴", desc: "∫x⁴ dx = x⁵/5 + C", tagColor: "#8b5cf6" },
    { title: "Differentiate 10x", desc: "d/dx (10x) = 10", tagColor: "#8b5cf6" },
    { title: "Integrate 8", desc: "∫8 dx = 8x + C", tagColor: "#8b5cf6" },
    { title: "Find derivative of x⁶", desc: "d/dx (x⁶) = 6x⁵", tagColor: "#8b5cf6" },
    { title: "Integrate 3x²", desc: "∫3x² dx = x³ + C", tagColor: "#8b5cf6" },
    { title: "Differentiate 12x³", desc: "d/dx (12x³) = 36x²", tagColor: "#8b5cf6" },
    { title: "Find limit of (x² - 25)/(x - 5) as x→5", desc: "Factor numerator: (x² - 25) = (x - 5)(x + 5). Cancel (x - 5). Result = x + 5. Put x = 5 → Limit = 10", tagColor: "#8b5cf6" },
    { title: "Integrate x⁵", desc: "∫x⁵ dx = x⁶/6 + C", tagColor: "#8b5cf6" },
    { title: "Differentiate 15x⁷", desc: "d/dx (15x⁷) = 105x⁶", tagColor: "#8b5cf6" },
    { title: "Find derivative of constant 20", desc: "d/dx (20) = 0", tagColor: "#8b5cf6" },
    { title: "Integrate 2x⁶", desc: "∫2x⁶ dx = 2x⁷/7 + C", tagColor: "#8b5cf6" },
    { title: "Find limit of (x² - 16)/(x - 4) as x→4", desc: "(x² - 16) = (x - 4)(x + 4). Cancel (x - 4). Result = x + 4. Put x = 4 → Limit = 8", tagColor: "#8b5cf6" },
    { title: "Differentiate x⁸", desc: "d/dx (x⁸) = 8x⁷", tagColor: "#8b5cf6" },
    { title: "Integrate 9x²", desc: "∫9x² dx = 3x³ + C", tagColor: "#8b5cf6" },
    { title: "Differentiate 4x⁹", desc: "d/dx (4x⁹) = 36x⁸", tagColor: "#8b5cf6" },
    { title: "Find limit of (x² - 9)/(x - 3) as x→3", desc: "(x² - 9) = (x - 3)(x + 3). Cancel (x - 3). Result = x + 3. Put x = 3 → Limit = 6", tagColor: "#8b5cf6" },
    { title: "Integrate x⁷", desc: "∫x⁷ dx = x⁸/8 + C", tagColor: "#8b5cf6" },
    { title: "Differentiate 11x⁴", desc: "d/dx (11x⁴) = 44x³", tagColor: "#8b5cf6" },
  ],
  physics: [
    { title: "Calculate Newton's Second Law force", desc: "Force = mass × acceleration (F = ma)", tagColor: "#22c55e" },
    { title: "Kinematic equation for displacement", desc: "d = vᵢt + 0.5at² — used for constant acceleration", tagColor: "#22c55e" },
    { title: "Calculate momentum", desc: "Momentum = mass × velocity (p = mv)", tagColor: "#22c55e" },
    { title: "Calculate kinetic energy", desc: "KE = 1/2 mv²", tagColor: "#22c55e" },
    { title: "Calculate gravitational force", desc: "F = Gm₁m₂ / r²", tagColor: "#22c55e" },
    { title: "Calculate weight of an object", desc: "Weight = mass × gravity (W = mg)", tagColor: "#22c55e" },
    { title: "Find velocity", desc: "Velocity = displacement / time (v = d/t)", tagColor: "#22c55e" },
    { title: "Find acceleration", desc: "Acceleration = change in velocity / time (a = (v - u) / t)", tagColor: "#22c55e" },
    { title: "Calculate power", desc: "Power = work / time (P = W/t)", tagColor: "#22c55e" },
    { title: "Calculate pressure", desc: "Pressure = force / area (P = F/A)", tagColor: "#22c55e" },
    { title: "Find density", desc: "Density = mass / volume (ρ = m/V)", tagColor: "#22c55e" },
    { title: "Calculate work done", desc: "Work = force × displacement (W = Fd)", tagColor: "#22c55e" },
    { title: "Find electric current", desc: "Current = charge / time (I = Q/t)", tagColor: "#22c55e" },
    { title: "Ohm’s Law", desc: "Voltage = current × resistance (V = IR)", tagColor: "#22c55e" },
    { title: "Calculate resistance", desc: "Resistance = voltage / current (R = V/I)", tagColor: "#22c55e" },
    { title: "Find frequency", desc: "Frequency = 1 / time period (f = 1/T)", tagColor: "#22c55e" },
    { title: "Calculate wave speed", desc: "Wave speed = frequency × wavelength (v = fλ)", tagColor: "#22c55e" },
    { title: "Find potential energy", desc: "PE = mgh", tagColor: "#22c55e" },
    { title: "Calculate centripetal force", desc: "F = mv² / r", tagColor: "#22c55e" },
    { title: "Find time using speed formula", desc: "Time = distance / speed (t = d/v)", tagColor: "#22c55e" },
    { title: "Calculate average speed", desc: "Average speed = total distance / total time", tagColor: "#22c55e" },
    { title: "Find displacement", desc: "Displacement = velocity × time (d = vt)", tagColor: "#22c55e" },
    { title: "Calculate mechanical efficiency", desc: "Efficiency = (output work / input work) × 100%", tagColor: "#22c55e" },
    { title: "Find elastic potential energy", desc: "PE = 1/2 kx²", tagColor: "#22c55e" },
    { title: "Calculate Coulomb force", desc: "F = k q₁ q₂ / r²", tagColor: "#22c55e" },
    { title: "Find angular velocity", desc: "ω = θ / t", tagColor: "#22c55e" },
    { title: "Calculate impulse", desc: "Impulse = force × time (J = Ft)", tagColor: "#22c55e" },
    { title: "Find heat energy", desc: "Q = mcΔT", tagColor: "#22c55e" },
    { title: "Stefan-Boltzmann Law", desc: "P = σ A T⁴", tagColor: "#22c55e" },
    { title: "Calculate Hooke’s Law force", desc: "F = -kx", tagColor: "#22c55e" },
    { title: "Find refractive index", desc: "n = c / v", tagColor: "#22c55e" },
    { title: "Calculate electric power", desc: "P = V I", tagColor: "#22c55e" },
    { title: "Find capacitance", desc: "C = Q / V", tagColor: "#22c55e" },
    { title: "Calculate magnetic force", desc: "F = q v B", tagColor: "#22c55e" },
    { title: "Einstein mass-energy equation", desc: "E = m c²", tagColor: "#22c55e" },
    { title: "Find escape velocity", desc: "v = √(2 G M / r)", tagColor: "#22c55e" },
    { title: "Calculate torque", desc: "Torque = force × distance (τ = F r)", tagColor: "#22c55e" },
    { title: "Find lens formula", desc: "1/f = 1/v + 1/u", tagColor: "#22c55e" },
  ],
  chemistry: [
    { title: "Balance chemical equations", desc: "Ensure same number of atoms on both sides. Example: 2H₂ + O₂ → 2H₂O", tagColor: "#eab308" },
    { title: "Ideal Gas Law calculation", desc: "PV = nRT — P=pressure, V=volume, n=moles, R=gas constant, T=temperature", tagColor: "#eab308" },
    { title: "Calculate molarity", desc: "Molarity = moles / volume (M = n/V)", tagColor: "#eab308" },
    { title: "Find number of moles", desc: "Moles = mass / molar mass (n = m/M)", tagColor: "#eab308" },
    { title: "Calculate density", desc: "Density = mass / volume (D = m/V)", tagColor: "#eab308" },
    { title: "Avogadro’s equation", desc: "Number of particles = moles × Avogadro constant (N = n × 6.022×10²³)", tagColor: "#eab308" },
    { title: "Boyle’s Law", desc: "P₁V₁ = P₂V₂", tagColor: "#eab308" },
    { title: "Charles’s Law", desc: "V₁/T₁ = V₂/T₂", tagColor: "#eab308" },
    { title: "Combined Gas Law", desc: "P₁V₁/T₁ = P₂V₂/T₂", tagColor: "#eab308" },
    { title: "Calculate percentage yield", desc: "% Yield = (actual yield / theoretical yield) × 100", tagColor: "#eab308" },
    { title: "Find empirical formula", desc: "Convert masses to moles, divide by smallest mole, use simplest whole number ratio.", tagColor: "#eab308" },
    { title: "Calculate pH", desc: "pH = -log[H⁺]", tagColor: "#eab308" },
    { title: "Calculate pOH", desc: "pOH = -log[OH⁻]", tagColor: "#eab308" },
    { title: "Water ion product", desc: "Kw = [H⁺][OH⁻] (Kw = 1.0 × 10⁻¹⁴)", tagColor: "#eab308" },
    { title: "Find heat energy", desc: "q = mcΔT", tagColor: "#eab308" },
    { title: "Calculate atomic mass", desc: "Atomic mass = Σ(isotope mass × abundance)", tagColor: "#eab308" },
    { title: "Henderson-Hasselbalch equation", desc: "pH = pKa + log([A⁻]/[HA])", tagColor: "#eab308" },
    { title: "Calculate concentration", desc: "Concentration = solute / solution volume", tagColor: "#eab308" },
    { title: "Raoult’s Law", desc: "Psolution = Xsolute × Psolvent", tagColor: "#eab308" },
    { title: "First-order reaction equation", desc: "ln[A] = ln[A₀] - kt", tagColor: "#eab308" },
    { title: "Calculate reaction rate", desc: "Rate = change in concentration / time", tagColor: "#eab308" },
    { title: "Faraday’s Law", desc: "m = (Q × M) / (n × F)", tagColor: "#eab308" },
    { title: "Nernst equation", desc: "E = E° - (0.0591/n)logQ", tagColor: "#eab308" },
    { title: "Calculate mole fraction", desc: "Mole fraction = moles of component / total moles", tagColor: "#eab308" },
    { title: "Find equilibrium constant", desc: "Kc = [products]/[reactants]", tagColor: "#eab308" },
    { title: "Arrhenius equation", desc: "k = A e^(-Ea/RT)", tagColor: "#eab308" },
  ],
  biology: [
    { title: "Describe stages of Mitosis", desc: "Stages: Prophase, Metaphase, Anaphase, Telophase. Produces identical daughter cells.", tagColor: "#ec4899" },
    { title: "Understand Photosynthesis equation", desc: "6CO₂ + 6H₂O + Light → C₆H₁₂O₆ + 6O₂ — Plants convert light energy into chemical energy.", tagColor: "#ec4899" },
    { title: "Cellular Respiration equation", desc: "C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + Energy", tagColor: "#ec4899" },
    { title: "DNA replication process", desc: "DNA unwinds. Complementary nucleotides pair with template strands. Two identical DNA molecules form.", tagColor: "#ec4899" },
    { title: "Stages of Meiosis", desc: "Meiosis I and Meiosis II — produces four haploid cells.", tagColor: "#ec4899" },
    { title: "Structure of DNA", desc: "Double helix made of nucleotides. Bases: A, T, G, C.", tagColor: "#ec4899" },
    { title: "Function of Ribosomes", desc: "Ribosomes synthesize proteins in the cell.", tagColor: "#ec4899" },
    { title: "Osmosis definition", desc: "Movement of water from high concentration to low concentration through a semipermeable membrane.", tagColor: "#ec4899" },
    { title: "Diffusion process", desc: "Movement of particles from high concentration to low concentration.", tagColor: "#ec4899" },
    { title: "ATP energy equation", desc: "ATP → ADP + Pi + Energy", tagColor: "#ec4899" },
    { title: "Hardy-Weinberg equation", desc: "p² + 2pq + q² = 1", tagColor: "#ec4899" },
    { title: "Function of Chloroplast", desc: "Chloroplast carries out photosynthesis in plant cells.", tagColor: "#ec4899" },
    { title: "Human heart chambers", desc: "Right atrium, Right ventricle, Left atrium, Left ventricle.", tagColor: "#ec4899" },
    { title: "Blood circulation pathway", desc: "Heart → Arteries → Capillaries → Veins → Heart", tagColor: "#ec4899" },
    { title: "Protein synthesis process", desc: "DNA → RNA → Protein", tagColor: "#ec4899" },
    { title: "Enzyme-substrate model", desc: "Enzymes bind substrates to speed up chemical reactions.", tagColor: "#ec4899" },
    { title: "Function of mitochondria", desc: "Mitochondria produce energy through cellular respiration.", tagColor: "#ec4899" },
    { title: "Punnett square probability", desc: "Used to predict genetic inheritance patterns.", tagColor: "#ec4899" },
    { title: "Ecological food chain", desc: "Producer → Primary consumer → Secondary consumer", tagColor: "#ec4899" },
    { title: "Law of Segregation", desc: "Alleles separate during gamete formation.", tagColor: "#ec4899" },
    { title: "Law of Independent Assortment", desc: "Genes assort independently during gamete formation.", tagColor: "#ec4899" },
    { title: "Function of White Blood Cells", desc: "White blood cells protect the body from infection.", tagColor: "#ec4899" },
    { title: "Transpiration process", desc: "Loss of water vapor from plant leaves.", tagColor: "#ec4899" },
    { title: "Natural selection concept", desc: "Organisms with favorable traits survive and reproduce.", tagColor: "#ec4899" },
    { title: "Nitrogen cycle process", desc: "Nitrogen moves through atmosphere, soil, and living organisms.", tagColor: "#ec4899" },
    { title: "Function of Red Blood Cells", desc: "Red blood cells transport oxygen using hemoglobin.", tagColor: "#ec4899" },
    { title: "Binary fission process", desc: "Asexual reproduction where one cell divides into two identical cells.", tagColor: "#ec4899" },
    { title: "Role of RNA", desc: "RNA carries genetic information for protein synthesis.", tagColor: "#ec4899" },
    { title: "Antibody function", desc: "Antibodies identify and neutralize harmful pathogens.", tagColor: "#ec4899" },
    { title: "Human digestive pathway", desc: "Mouth → Esophagus → Stomach → Intestine → Rectum", tagColor: "#ec4899" },
  ],
  economics: [
    { title: "Law of Supply and Demand", desc: "If demand increases and supply remains unchanged, price rises.", tagColor: "#06b6d4" },
    { title: "Calculate Gross Domestic Product (GDP)", desc: "GDP = Consumption + Investment + Government Spending + (Exports - Imports)", tagColor: "#06b6d4" },
    { title: "Calculate inflation rate", desc: "Inflation Rate = ((New CPI - Old CPI) / Old CPI) × 100", tagColor: "#06b6d4" },
    { title: "Calculate price elasticity of demand", desc: "Elasticity = % Change in Quantity Demanded / % Change in Price", tagColor: "#06b6d4" },
    { title: "Find average cost", desc: "Average Cost = Total Cost / Quantity", tagColor: "#06b6d4" },
    { title: "Calculate marginal cost", desc: "Marginal Cost = Change in Total Cost / Change in Quantity", tagColor: "#06b6d4" },
    { title: "Calculate revenue", desc: "Revenue = Price × Quantity", tagColor: "#06b6d4" },
    { title: "Find profit", desc: "Profit = Total Revenue - Total Cost", tagColor: "#06b6d4" },
    { title: "Calculate opportunity cost", desc: "Opportunity cost is the value of the next best alternative.", tagColor: "#06b6d4" },
    { title: "Find unemployment rate", desc: "Unemployment Rate = (Unemployed / Labor Force) × 100", tagColor: "#06b6d4" },
    { title: "Calculate per capita income", desc: "Per Capita Income = National Income / Population", tagColor: "#06b6d4" },
    { title: "Law of Diminishing Marginal Utility", desc: "As consumption increases, additional satisfaction decreases.", tagColor: "#06b6d4" },
    { title: "Calculate marginal revenue", desc: "Marginal Revenue = Change in Total Revenue / Change in Quantity", tagColor: "#06b6d4" },
    { title: "Find consumer surplus", desc: "Consumer Surplus = Willingness to Pay - Actual Price", tagColor: "#06b6d4" },
    { title: "Find producer surplus", desc: "Producer Surplus = Selling Price - Minimum Acceptable Price", tagColor: "#06b6d4" },
    { title: "Calculate savings", desc: "Savings = Income - Consumption", tagColor: "#06b6d4" },
    { title: "Find break-even point", desc: "Break-even Point = Fixed Cost / (Price - Variable Cost)", tagColor: "#06b6d4" },
    { title: "Calculate trade balance", desc: "Trade Balance = Exports - Imports", tagColor: "#06b6d4" },
    { title: "Law of Scarcity", desc: "Resources are limited but human wants are unlimited.", tagColor: "#06b6d4" },
    { title: "Calculate average revenue", desc: "Average Revenue = Total Revenue / Quantity", tagColor: "#06b6d4" },
    { title: "Find nominal GDP", desc: "Nominal GDP uses current market prices.", tagColor: "#06b6d4" },
    { title: "Find real GDP", desc: "Real GDP uses constant base-year prices.", tagColor: "#06b6d4" },
    { title: "Calculate GDP deflator", desc: "GDP Deflator = (Nominal GDP / Real GDP) × 100", tagColor: "#06b6d4" },
    { title: "Law of Comparative Advantage", desc: "Countries benefit by specializing in goods with lower opportunity cost.", tagColor: "#06b6d4" },
    { title: "Calculate disposable income", desc: "Disposable Income = Income - Taxes", tagColor: "#06b6d4" },
    { title: "Find average propensity to consume", desc: "APC = Consumption / Income", tagColor: "#06b6d4" },
    { title: "Find marginal propensity to consume", desc: "MPC = Change in Consumption / Change in Income", tagColor: "#06b6d4" },
    { title: "Calculate equilibrium price", desc: "Equilibrium occurs where demand equals supply.", tagColor: "#06b6d4" },
    { title: "Law of Demand", desc: "When price increases, demand decreases.", tagColor: "#06b6d4" },
    { title: "Calculate national income", desc: "National Income = GDP - Depreciation - Indirect Taxes + Subsidies", tagColor: "#06b6d4" },
  ],
  literature: [
    { title: "Identify metaphorical imagery in Shakespeare", desc: "“To be or not to be” reflects the struggle between life and death.", tagColor: "#f97316" },
    { title: "Contrast Protagonist and Antagonist development", desc: "The protagonist drives the story forward, while the antagonist creates conflict.", tagColor: "#f97316" },
    { title: "Define symbolism in literature", desc: "Symbolism uses objects or actions to represent deeper meanings.", tagColor: "#f97316" },
    { title: "Explain dramatic irony", desc: "The audience knows information that characters do not know.", tagColor: "#f97316" },
    { title: "Identify theme in a story", desc: "Theme is the central message or underlying idea of a literary work.", tagColor: "#f97316" },
    { title: "Define foreshadowing", desc: "Foreshadowing gives hints about future events in the story.", tagColor: "#f97316" },
    { title: "Explain personification", desc: "Personification gives human qualities to non-human objects.", tagColor: "#f97316" },
    { title: "Analyze simile in poetry", desc: "A simile compares two things using “like” or “as.”", tagColor: "#f97316" },
    { title: "Define alliteration", desc: "Alliteration is repetition of beginning consonant sounds.", tagColor: "#f97316" },
    { title: "Explain hyperbole", desc: "Hyperbole is an exaggerated statement used for emphasis.", tagColor: "#f97316" },
    { title: "Define oxymoron", desc: "An oxymoron combines opposite words together.", tagColor: "#f97316" },
    { title: "Analyze irony in literature", desc: "Irony occurs when expectation differs from reality.", tagColor: "#f97316" },
    { title: "Define tragic hero", desc: "A tragic hero has a fatal flaw leading to downfall.", tagColor: "#f97316" },
    { title: "Explain narrative perspective", desc: "Narrative perspective determines who tells the story.", tagColor: "#f97316" },
    { title: "Differentiate first-person narration", desc: "First-person narration uses “I” and tells events personally.", tagColor: "#f97316" },
    { title: "Define third-person omniscient narration", desc: "The narrator knows thoughts and feelings of all characters.", tagColor: "#f97316" },
    { title: "Analyze conflict in literature", desc: "Conflict is the struggle between opposing forces.", tagColor: "#f97316" },
    { title: "Define climax in a story", desc: "Climax is the turning point of the narrative.", tagColor: "#f97316" },
    { title: "Explain resolution in literature", desc: "Resolution is the conclusion where conflicts are solved.", tagColor: "#f97316" },
    { title: "Identify rhyme scheme", desc: "Rhyme scheme is the pattern of rhymes in poetry.", tagColor: "#f97316" },
    { title: "Define blank verse", desc: "Blank verse is unrhymed poetry written in iambic pentameter.", tagColor: "#f97316" },
    { title: "Analyze Shakespearean sonnet structure", desc: "A Shakespearean sonnet has 14 lines with rhyme scheme ABAB CDCD EFEF GG.", tagColor: "#f97316" },
    { title: "Define satire", desc: "Satire uses humor or criticism to expose weaknesses.", tagColor: "#f97316" },
    { title: "Explain motif in literature", desc: "A motif is a repeated idea or symbol in a text.", tagColor: "#f97316" },
    { title: "Define allegory", desc: "An allegory is a story with symbolic meaning.", tagColor: "#f97316" },
    { title: "Analyze character development", desc: "Character development shows growth or change over time.", tagColor: "#f97316" },
    { title: "Define setting in literature", desc: "Setting describes time and place of the story.", tagColor: "#f97316" },
    { title: "Explain mood in literature", desc: "Mood is the emotional atmosphere of a literary work.", tagColor: "#f97316" },
    { title: "Define tone in writing", desc: "Tone reflects the author’s attitude toward the subject.", tagColor: "#f97316" },
    { title: "Analyze epic hero characteristics", desc: "An epic hero shows bravery, strength, and noble qualities.", tagColor: "#f97316" },
  ],
  business: [
    { title: "Construct a SWOT analysis matrix", desc: "SWOT stands for Strengths, Weaknesses, Opportunities, and Threats.", tagColor: "#14b8a6" },
    { title: "Explain time value of money", desc: "Money today is worth more than the same amount in the future.", tagColor: "#14b8a6" },
    { title: "Calculate profit", desc: "Profit = Revenue - Cost", tagColor: "#14b8a6" },
    { title: "Calculate total revenue", desc: "Total Revenue = Price × Quantity Sold", tagColor: "#14b8a6" },
    { title: "Find break-even point", desc: "Break-even Point = Fixed Cost / (Selling Price - Variable Cost)", tagColor: "#14b8a6" },
    { title: "Explain market segmentation", desc: "Market segmentation divides customers into smaller target groups.", tagColor: "#14b8a6" },
    { title: "Define branding", desc: "Branding creates a unique identity for a business or product.", tagColor: "#14b8a6" },
    { title: "Explain supply chain management", desc: "Supply chain management controls product flow from supplier to customer.", tagColor: "#14b8a6" },
    { title: "Calculate return on investment", desc: "ROI = (Profit / Investment) × 100", tagColor: "#14b8a6" },
    { title: "Define entrepreneurship", desc: "Entrepreneurship is starting and managing a business venture.", tagColor: "#14b8a6" },
    { title: "Explain customer satisfaction", desc: "Customer satisfaction measures how products meet customer expectations.", tagColor: "#14b8a6" },
    { title: "Calculate net income", desc: "Net Income = Total Revenue - Total Expenses", tagColor: "#14b8a6" },
    { title: "Define market share", desc: "Market Share = Company Sales / Total Market Sales", tagColor: "#14b8a6" },
    { title: "Explain business ethics", desc: "Business ethics are moral principles guiding business behavior.", tagColor: "#14b8a6" },
    { title: "Calculate gross profit", desc: "Gross Profit = Sales Revenue - Cost of Goods Sold", tagColor: "#14b8a6" },
    { title: "Define monopoly market", desc: "A monopoly exists when one seller controls the entire market.", tagColor: "#14b8a6" },
    { title: "Explain leadership styles", desc: "Leadership styles determine how managers guide employees.", tagColor: "#14b8a6" },
    { title: "Calculate operating profit", desc: "Operating Profit = Gross Profit - Operating Expenses", tagColor: "#14b8a6" },
    { title: "Define balance sheet", desc: "A balance sheet shows assets, liabilities, and equity.", tagColor: "#14b8a6" },
    { title: "Accounting equation", desc: "Assets = Liabilities + Owner’s Equity", tagColor: "#14b8a6" },
    { title: "Explain liquidity", desc: "Liquidity measures ability to pay short-term obligations.", tagColor: "#14b8a6" },
    { title: "Calculate current ratio", desc: "Current Ratio = Current Assets / Current Liabilities", tagColor: "#14b8a6" },
    { title: "Define human resource management", desc: "HRM manages employee recruitment, training, and performance.", tagColor: "#14b8a6" },
    { title: "Explain promotional mix", desc: "Promotional mix includes advertising, sales promotion, and public relations.", tagColor: "#14b8a6" },
    { title: "Calculate depreciation", desc: "Depreciation = (Cost - Salvage Value) / Useful Life", tagColor: "#14b8a6" },
    { title: "Define economies of scale", desc: "Average cost decreases as production increases.", tagColor: "#14b8a6" },
    { title: "Explain cash flow", desc: "Cash flow tracks money entering and leaving a business.", tagColor: "#14b8a6" },
    { title: "Calculate inventory turnover", desc: "Inventory Turnover = Cost of Goods Sold / Average Inventory", tagColor: "#14b8a6" },
    { title: "Define corporate social responsibility", desc: "CSR means businesses contribute positively to society.", tagColor: "#14b8a6" },
    { title: "Explain competitive advantage", desc: "Competitive advantage helps a business outperform competitors.", tagColor: "#14b8a6" },
  ],
  writing: [
    { title: "Structure an argumentative essay outline", desc: "Introduction with thesis, body paragraphs with evidence, counterargument, and conclusion.", tagColor: "#6366f1" },
    { title: "Active vs Passive voice revision", desc: "Use active voice for direct and clear writing. Example: “The student wrote the essay.”", tagColor: "#6366f1" },
    { title: "Define thesis statement", desc: "A thesis statement presents the main argument of an essay.", tagColor: "#6366f1" },
    { title: "Structure a paragraph", desc: "Topic sentence, supporting details, and concluding sentence.", tagColor: "#6366f1" },
    { title: "Explain topic sentence", desc: "A topic sentence introduces the main idea of a paragraph.", tagColor: "#6366f1" },
    { title: "Define conclusion paragraph", desc: "A conclusion summarizes key points and restates the thesis.", tagColor: "#6366f1" },
    { title: "Use transition words", desc: "Transition words connect ideas smoothly in writing.", tagColor: "#6366f1" },
    { title: "Identify narrative writing", desc: "Narrative writing tells a story with characters and events.", tagColor: "#6366f1" },
    { title: "Explain descriptive writing", desc: "Descriptive writing uses vivid details to describe people or places.", tagColor: "#6366f1" },
    { title: "Define expository writing", desc: "Expository writing explains information clearly and logically.", tagColor: "#6366f1" },
    { title: "Understand persuasive writing", desc: "Persuasive writing aims to convince readers of a viewpoint.", tagColor: "#6366f1" },
    { title: "Correct run-on sentence", desc: "Split long sentences into shorter complete sentences.", tagColor: "#6366f1" },
    { title: "Identify fragment sentence", desc: "A fragment lacks a complete subject or verb.", tagColor: "#6366f1" },
    { title: "Use proper punctuation", desc: "Punctuation improves clarity and readability in writing.", tagColor: "#6366f1" },
    { title: "Explain citation purpose", desc: "Citations give credit to original sources.", tagColor: "#6366f1" },
    { title: "Define plagiarism", desc: "Plagiarism is copying another person’s work without credit.", tagColor: "#6366f1" },
    { title: "Use formal academic tone", desc: "Academic tone avoids slang and informal expressions.", tagColor: "#6366f1" },
    { title: "Identify supporting evidence", desc: "Supporting evidence strengthens the main argument.", tagColor: "#6366f1" },
    { title: "Explain paraphrasing", desc: "Paraphrasing rewrites ideas using different words.", tagColor: "#6366f1" },
    { title: "Define summarizing", desc: "Summarizing gives the main ideas briefly.", tagColor: "#6366f1" },
    { title: "Understand compare and contrast essay", desc: "Compare and contrast essays discuss similarities and differences.", tagColor: "#6366f1" },
    { title: "Explain hook statement", desc: "A hook grabs the reader’s attention at the beginning.", tagColor: "#6366f1" },
    { title: "Identify audience in writing", desc: "Audience refers to the intended readers of a text.", tagColor: "#6366f1" },
  ],
};

export default function ResourceCategoryPage() {
  const params = useParams();
  const { t } = useLanguage();
  const categoryParam = String(params?.category || "math").toLowerCase();

  const title = categoryParam.charAt(0).toUpperCase() + categoryParam.slice(1);
  const resources = sampleResourcesByCategory[categoryParam] || sampleResourcesByCategory.math;

  return (
    <div className="resources-page-container">
      <style>{`
        .resources-page-container {
          padding: 28px 32px;
        }
        @media (max-width: 768px) {
          .resources-page-container {
            padding: 20px 16px;
          }
        }
      `}</style>
      <h2 style={{ color: "#ffffff", fontSize: "24px", fontWeight: 700, margin: "0 0 28px" }}>
        {t(title)} - {t("Equation")}
      </h2>

      <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
        {resources.map((item, i) => (
          <div
            key={i}
            style={{
              backgroundColor: "#111118",
              borderRadius: "14px",
              border: "1px solid rgba(255,255,255,0.06)",
              padding: "24px",
              cursor: "pointer",
              transition: "all 0.2s ease",
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.borderColor = "rgba(79,70,229,0.3)";
              e.currentTarget.style.transform = "translateX(4px)";
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.borderColor = "rgba(255,255,255,0.06)";
              e.currentTarget.style.transform = "translateX(0)";
            }}
          >
            {/* Category Tag */}
            <span
              style={{
                display: "inline-block",
                padding: "4px 12px",
                borderRadius: "14px",
                backgroundColor: `${item.tagColor}25`,
                color: item.tagColor,
                fontSize: "11px",
                fontWeight: 600,
                marginBottom: "12px",
                textTransform: "uppercase",
              }}
            >
              {t(title)}
            </span>

            <h3 style={{ color: "#ffffff", fontSize: "16px", fontWeight: 600, margin: "0 0 8px" }}>
              {item.title}
            </h3>
            <p style={{ color: "rgba(255,255,255,0.4)", fontSize: "13px", margin: 0, lineHeight: 1.6 }}>
              {item.desc}
            </p>
          </div>
        ))}
      </div>
    </div>
  );
}
